on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: id
      - run: lscpu
      - run: free -h
      - run: cat /proc/sys/kernel/unprivileged_userns_clone
      - run: sudo sysctl -w kernel.unprivileged_userns_clone=1
      - run: cat /proc/sys/kernel/unprivileged_userns_clone
      - run: cat /proc/sys/user/max_user_namespaces
      - run: cat /proc/sys/kernel/apparmor_restrict_unprivileged_userns || true
      - run: cat /etc/sysctl.d/*
      - run: cat /etc/sysctl.conf
